repos:
  # 1. Validações básicas de arquivos (evita commits com lixo)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  # 2. Validações automáticas de Terraform (Formatação)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt #Identação do código
      - id: terraform_tflint #Linter de boas práticas e erros potenciais
      - id: terraform_trivy #Análise estática de segurança
      - id: terraform_docs #Gera/atualiza README.md a partir dos .tf
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
